# -*- coding: utf-8 -*-
"""Ré-applique price_weighted + repli zone + import Zones dans RatesManager."""
import io

p = r"C:\Users\Derouiche Oussama\Plugins COD Algérien\infinitycod\includes\shipping\class-rates-manager.php"
BS = chr(92)
with io.open(p, "r", encoding="utf-8", newline="") as f:
    d = f.read()

# 1) Import Zones.
old_use = "use InfinityCod" + BS + "Core" + BS + "Schema;\nuse InfinityCod" + BS + "Core" + BS + "Settings;"
new_use = old_use + "\nuse InfinityCod" + BS + "Shipping" + BS + "Zones;"
if d.count(new_use) == 0:
    assert d.count(old_use) == 1, "use : %d" % d.count(old_use)
    d = d.replace(old_use, new_use, 1)

# 2) Repli zone + price_weighted + weight_tiers + return_fee.
old = (
    "\t\tif ( (float) $wilaya['price'] >= 0 ) {\n"
    "\t\t\treturn (float) $wilaya['price'];\n"
    "\t\t}\n\n"
    "\t\t// 3. Défaut global.\n"
    "\t\t$fallback = ( self::MODE_DESK === $mode ) ? 'default_price_desk' : 'default_price_home';\n"
    "\t\treturn (float) Settings::get( $fallback, 0 );\n"
    "\t}"
)
new = (
    "\t\tif ( (float) $wilaya['price'] >= 0 ) {\n"
    "\t\t\treturn (float) $wilaya['price'];\n"
    "\t\t}\n\n"
    "\t\t// 3. Repli zone régionale (wilaya en mode « hérite »).\n"
    "\t\t$zone_price = Zones::price( $wilaya_code, $mode );\n"
    "\t\tif ( null !== $zone_price ) {\n"
    "\t\t\treturn $zone_price;\n"
    "\t\t}\n\n"
    "\t\t// 4. Défaut global.\n"
    "\t\t$fallback = ( self::MODE_DESK === $mode ) ? 'default_price_desk' : 'default_price_home';\n"
    "\t\treturn (float) Settings::get( $fallback, 0 );\n"
    "\t}\n\n"
    "\t/**\n"
    "\t * Tarif avec paliers de poids par wilaya (0-1 / 1-5 / 5-10 kg, puis /kg).\n"
    "\t *\n"
    "\t * Retourne null quand aucun palier n'est configuré : l'appelant applique\n"
    "\t * alors le tarif de base + le supplément poids global (comportement\n"
    "\t * historique). Un palier configuré REMPLACE le tarif de base.\n"
    "\t *\n"
    "\t * @param string $wilaya_code Code wilaya.\n"
    "\t * @param string $commune     Nom de commune (override éventuel).\n"
    "\t * @param string $mode        'home' ou 'desk'.\n"
    "\t * @param float  $weight      Poids total (kg).\n"
    "\t * @return float|null\n"
    "\t */\n"
    "\tpublic function price_weighted( $wilaya_code, $commune, $mode, $weight ) {\n"
    "\t\t$weight = max( 0.0, (float) $weight );\n"
    "\t\tif ( $weight <= 0 ) {\n"
    "\t\t\treturn null;\n"
    "\t\t}\n\n"
    "\t\t$tiers = $this->weight_tiers( $wilaya_code );\n"
    "\t\tif ( null === $tiers ) {\n"
    "\t\t\treturn null;\n"
    "\t\t}\n\n"
    "\t\t// Base : cascade commune > wilaya > zone > défaut (sans poids).\n"
    "\t\t$base = $this->price( $wilaya_code, $commune, $mode );\n"
    "\t\tif ( $base < 0 ) {\n"
    "\t\t\treturn null;\n"
    "\t\t}\n\n"
    "\t\tif ( $weight <= 1 ) {\n"
    "\t\t\treturn $tiers['w1'] >= 0 ? $tiers['w1'] : $base;\n"
    "\t\t}\n"
    "\t\tif ( $weight <= 5 ) {\n"
    "\t\t\treturn $tiers['w5'] >= 0 ? $tiers['w5'] : ( $tiers['w1'] >= 0 ? $tiers['w1'] : $base );\n"
    "\t\t}\n"
    "\t\tif ( $weight <= 10 ) {\n"
    "\t\t\treturn $tiers['w10'] >= 0 ? $tiers['w10'] : ( $tiers['w5'] >= 0 ? $tiers['w5'] : $base );\n"
    "\t\t}\n"
    "\t\t// Au-delà de 10 kg : tarif du palier 5-10 (ou base) + prix par kg.\n"
    "\t\t$over_base = $tiers['w10'] >= 0 ? $tiers['w10'] : ( $tiers['w5'] >= 0 ? $tiers['w5'] : $base );\n"
    "\t\treturn round( $over_base + ( ( $weight - 10 ) * $tiers['w_over'] ), 2 );\n"
    "\t}\n\n"
    "\t/**\n"
    "\t * Paliers de poids d'une wilaya (null si aucun palier défini).\n"
    "\t *\n"
    "\t * @param string $wilaya_code Code wilaya.\n"
    "\t * @return array{w1:float,w5:float,w10:float,w_over:float}|null\n"
    "\t */\n"
    "\tpublic function weight_tiers( $wilaya_code ) {\n"
    "\t\tglobal $wpdb;\n"
    "\t\t$table = Schema::table( 'wilayas' );\n"
    "\t\tstatic $cache_tiers = array();\n"
    "\t\tif ( ! isset( $cache_tiers[ $wilaya_code ] ) ) {\n"
    "\t\t\t$cache_tiers[ $wilaya_code ] = $wpdb->get_row(\n"
    "\t\t\t\t$wpdb->prepare( \"SELECT w5, w10, w_over FROM {$table} WHERE code = %s\", $wilaya_code ), // phpcs:ignore WordPress.DB.PreparedSQL\n"
    "\t\t\t\tARRAY_A\n"
    "\t\t\t);\n"
    "\t\t}\n"
    "\t\t$row = $cache_tiers[ $wilaya_code ];\n"
    "\t\tif ( ! is_array( $row ) ) {\n"
    "\t\t\treturn null;\n"
    "\t\t}\n"
    "\t\t$tiers = array(\n"
    "\t\t\t'w1'     => -1.0, // Palier 0-1 kg : hérite toujours du tarif de base.\n"
    "\t\t\t'w5'     => (float) $row['w5'],\n"
    "\t\t\t'w10'    => (float) $row['w10'],\n"
    "\t\t\t'w_over' => (float) $row['w_over'],\n"
    "\t\t);\n"
    "\t\tif ( $tiers['w5'] < 0 && $tiers['w10'] < 0 && $tiers['w_over'] <= 0 ) {\n"
    "\t\t\treturn null;\n"
    "\t\t}\n"
    "\t\treturn $tiers;\n"
    "\t}\n\n"
    "\t/**\n"
    "\t * Frais de retour configurés pour une wilaya (provision P&L).\n"
    "\t *\n"
    "\t * @param string $wilaya_code Code wilaya.\n"
    "\t * @return float\n"
    "\t */\n"
    "\tpublic function return_fee( $wilaya_code ) {\n"
    "\t\tglobal $wpdb;\n"
    "\t\t$table = Schema::table( 'wilayas' );\n"
    "\t\tstatic $cache_ret = array();\n"
    "\t\tif ( ! isset( $cache_ret[ $wilaya_code ] ) ) {\n"
    "\t\t\t$cache_ret[ $wilaya_code ] = $wpdb->get_var( $wpdb->prepare( \"SELECT return_fee FROM {$table} WHERE code = %s\", $wilaya_code ) );\n"
    "\t\t}\n"
    "\t\treturn max( 0, (float) $cache_ret[ $wilaya_code ] );\n"
    "\t}"
)
assert d.count(old) == 1, "ancres price : %d" % d.count(old)
d = d.replace(old, new, 1)

with io.open(p, "w", encoding="utf-8", newline="") as f:
    f.write(d)
print("OK RatesManager : price_weighted + zones + tiers + return_fee")
